<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615120656 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_recipe_tag (recipe_id INT NOT NULL, recipe_tag_id INT NOT NULL, PRIMARY KEY (recipe_id, recipe_tag_id))');
        $this->addSql('CREATE INDEX IDX_3BA055AC59D8A214 ON recipe_recipe_tag (recipe_id)');
        $this->addSql('CREATE INDEX IDX_3BA055AC37CC7D30 ON recipe_recipe_tag (recipe_tag_id)');
        $this->addSql('CREATE TABLE recipe_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE recipe_recipe_tag ADD CONSTRAINT FK_3BA055AC59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recipe_recipe_tag ADD CONSTRAINT FK_3BA055AC37CC7D30 FOREIGN KEY (recipe_tag_id) REFERENCES recipe_tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_recipe_tag DROP CONSTRAINT FK_3BA055AC59D8A214');
        $this->addSql('ALTER TABLE recipe_recipe_tag DROP CONSTRAINT FK_3BA055AC37CC7D30');
        $this->addSql('DROP TABLE recipe_recipe_tag');
        $this->addSql('DROP TABLE recipe_tag');
    }
}
