<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617110847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe_saved (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recipe_id INT NOT NULL, acount_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EFF0073A59D8A214 ON recipe_saved (recipe_id)');
        $this->addSql('CREATE INDEX IDX_EFF0073A8E3B64AA ON recipe_saved (acount_id)');
        $this->addSql('ALTER TABLE recipe_saved ADD CONSTRAINT FK_EFF0073A59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe_saved ADD CONSTRAINT FK_EFF0073A8E3B64AA FOREIGN KEY (acount_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipe_saved DROP CONSTRAINT FK_EFF0073A59D8A214');
        $this->addSql('ALTER TABLE recipe_saved DROP CONSTRAINT FK_EFF0073A8E3B64AA');
        $this->addSql('DROP TABLE recipe_saved');
    }
}
